name: reviewdog
on: pull_request

jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - uses: actions/checkout@v2
      - name: Setup Go
        run: echo ::add-path::$(go env GOPATH)/bin
      - name: Install linters
        run: go get golang.org/x/lint/golint
      - uses: reviewdog/action-setup@v1
      - name: Run reviewdog
        continue-on-error: true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -reporter=github-pr-check
