name: reviewdog
on: pull_request

jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1
      - name: Install golint
        run: |
          GO111MODULE=off GOBIN=$(pwd)/bin go get golang.org/x/lint/golint
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -reporter=github-pr-check -runners=golint,govet
